FROM python:3.12-slim
RUN pip install --no-cache-dir dbt-core==1.10.11 dbt-snowflake==1.10.2
RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*
WORKDIR /app/dbt
COPY dbt /app/dbt
ENTRYPOINT ["dbt"]
CMD ["build"]
